Add `rustls-mbedpki-provider` crate
fortanix/rustls-mbedtls-provider pull request #1
Opened 2023-10-31 18:24 UTC by s-arash

2023-11-01 19:02 UTC, Taowyoo requested changes
Except the comments I left.
I suggest including https://github.com/rustls/rustls/blob/main/.rustfmt.toml in the PR and format code before merge.

Also I think pub exposed functions and types should be documented, especially for:
- rustls-mbedpki-provider/src/client_cert_verifier.rs
- rustls-mbedpki-provider/src/server_cert_verifier.rs

2023-11-01 19:04 UTC, Taowyoo commented
Also please remember to resolve the conflict by merge master to this branch (this is fine since we will squash merge this PR)

2023-11-01 20:12 UTC, s-arash commented on rustls-mbedpki-provider/Cargo.toml
Hmm, for lib crates is that the preferred approach? I ask because I think lib crates should work with any sem-ver-compatible version of their dependencies.

2023-11-01 20:39 UTC, s-arash commented on rustls-mbedpki-provider/src/server_cert_verifier.rs
> +        // This will be handled in https://fortanix.atlassian.net/browse/PM-176
copy pasta error!

2023-11-01 21:23 UTC, s-arash commented on rustls-mbedpki-provider/Cargo.toml
> +rustls-pemfile = "1.0"
Done

2023-11-01 21:23 UTC, s-arash commented on rustls-mbedpki-provider/src/client_cert_verifier.rs
> +        assert!(verifier.verify_client_cert(&cert_chain[0], &cert_chain[1..], now).is_err());
Done

2023-11-01 21:24 UTC, s-arash commented on rustls-mbedpki-provider/src/lib.rs
> +        mbedtls::Error::X509CertUnknownFormat |
Done!

2023-11-01 23:01 UTC, Taowyoo commented on rustls-mbedpki-provider/Cargo.toml
I think the reason is mainly for CI. It help trace the dependencies and build error when incomparable issue happened (like GitHub's dependent bot will help check update and security vulnerability based on Cargo.toml and Cargo.lock ).
Because for user of this crates, they already generate a new lock file their project.

2023-11-01 23:07 UTC, Taowyoo approved these changes
LGTM

2023-11-01 23:08 UTC, Taowyoo commented on rustls-mbedpki-provider/Cargo.toml
I will merge this crate into workspace after the crypto provider PR is merged

2023-11-01 23:09 UTC, merged

2023-11-02 00:39 UTC, s-arash commented on rustls-mbedpki-provider/Cargo.toml
I see. I guess my point is: the libs should work with newer sem-ver compatible versions of their dependencies as well (which is what could happen in the CI). But I see your point. We don't want a situation where CI passes today and fails tomorrow while our code has not changed.